---
title: "PO2PLS_run"
author: "Sanne"
date: "November 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r}
# Get packages
library(OmicsPLS)
library(data.table)
library(PO2PLS)
source("Functions.R")
# Set seed
set.seed(31*12*2016)
# Set number of participants
np=1358

# Draw subjects
sample <- sort(sample(1:np, 1000))
```

# Finding the optimal number of components
```{r}
dim_names <- list(chromosomes=1:22, components=c("r", "rx", "ry"))
best_comp <- matrix(rep(0, 22*3), nrow = 22, ncol = 3, dimnames = dim_names)
for(i in 1:22){
  # Load the chromosome data
  setwd("C:/Users/rikul/Documents/Thesis_data")
  filename <- paste("Xy_chr", i, ".Rdata", sep="")
  load(filename)
  X <- as.data.frame(X)
  y <- as.data.frame(y)
  
  # Create training set
  Xtrain <- X[sample,]
  ytrain <- y[sample,]
  
  # Cross-validate (O2PLS function, replace with PO2PLs version)
  best_comp[i,] <- max_logl_PO2PLS(Xtrain, ytrain, 7, 7, 7)$maximum[1,]
}
save(best_comp,"best_comp", file="Components.Rdata")
```


```{r}
set.seed(23274)
for(i in 1:22){
  # Load the chromosome data
  setwd("C:/Users/rikul/Documents/Thesis_data")
  filename <- paste("Xy_chr", i, ".Rdata", sep="")
  load(filename)
  X <- as.data.frame(X)
  y <- as.data.frame(y)
  
  # Create training set
  Xtrain <- X[sample,]
  ytrain <- y[sample,]
  
  # Run PO2PLS
  comps <- best_comp[i,]
  Psteps2000 <- PO2PLS(as.matrix(Xtrain), as.matrix(ytrain), comps[1], comps[2], comps[3], steps=2000, init_param = "random")
  output_file <- paste("PO2PLS_chr", i, ".Rdata", sep="")
  save(Psteps2000, "Psteps2000", file=output_file)
}
```






# Running PO2PLS

```{r}
```


```{r}
summary(Psteps2000_x1)
param <- Psteps2000_x1$parameters
```

```{r}
# Plot results
#plot(param$W[,1], param$W[,2], xlab="First component", ylab="Second component")
#abline(h=0)
#abline(v=0)
#plot(param$C[,1], param$C[,2], pch=as.character(1:7), xlab="First component", ylab="Second component")
#abline(h=0)
#abline(v=0)

param <- Psteps2000_x1$parameters
plot(param$W[,1])
which.max(param$W[,1])
which.max(param$Wo[,3])
plot(param$Wo[,1])
plot(param$Wo[,2])
plot(param$Wo[,3])
plot(colMeans(Xtrain))
sd(Xtrain%*%param$W[,1])
sd(colSums(Xtrain))/sqrt(ncol(Xtrain))

colnames(Xtrain)[3350:3400]
```
```{r}
plot(param$W[,1], ylab="First component", main="Genes")
abline(h=0)
#plot(param$W[,2], ylab="Second component", main="Genes")
#abline(h=0)
plot(param$C[,1], ylab="First component", pch=as.character(1:7), main="Outcomes")
abline(h=0)
#plot(param$C[,2], ylab="Second component", pch=as.character(1:7), main="Outcomes")
#abline(h=0)
```

```{r}
# Compare with O2PLS results
O2PLS_res <- o2m(Xtrain, ytrain, 1, 3, 4)
summary(O2PLS_res)
# Plot joined components
plot(O2PLS_res, "Xj")
plot(O2PLS_res, "Yj")

# Plot specific component of X
plot(O2PLS_res, "Xo")

# It seems there is one area with extreme values, which ended up in the specific part in O2PLS and in the joined part in PO2PLS
```



To do

Gene Ontology (GO, look into it)
>GSEA (look into it) MAGMA/VEGAS
With specific parts and without specific parts (0)
Top genes!
```

