---
title: "PO2PLS_run"
author: "Sanne"
date: "November 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r}
# Get packages
library(OmicsPLS)
library(data.table)
library(PO2PLS)
# Set seed
set.seed(31*12*2016)

# Load the chromosome 10 data
setwd("C:/Users/rikul/Documents/Thesis_data")
load("Xy_chr10.Rdata")

# 1358 participants
# Chromosome 1: 15946
# Chromosome 2: 12805
# Chromosome 3: 10153
# Chromosome 4: 8124
# Chromosome 5: 9519
# Chromosome 6: 8516
# Chromosome 7: 8929
# Chromosome 8: 7683
# Chromosome 9: 6720
# Chromosome 10: 7571
# Chromosome 11: 9708
# Chromosome 12: 9347
# Chromosome 13: 4353 
# Chromosome 14: 6180
# Chromosome 15: 5869
# Chromosome 16: 5848
# Chromosome 17: 6712
# Chromosome 18: 3927
# Chromosome 19: 6332
# Chromosome 20: 4404
# Chromosome 21: 2145
# Chromosome 22: 3545

15946 + 12805 + 10153 + 8124 + 9519 + 8516 + 8929 + 7638 + 6720 + 7571 + 9708 + 9347 + 4353 + 6180 + 5869 + 5848 + 6712 + 3927 + 6332 + 4404 + 2145 + 3545
# Draw subjects
sample <- sort(sample(1:nrow(X), 1000))

# Filter subjects
Xtrain <- X[sample,]
ytrain <- y[sample,]
```



# Cross-validation


```{r}
#Crossvalidation with max. 3 components
crossval_o2m_adjR2(Xtrain, ytrain, 1:3, 0:3, 0:3, nr_folds=5)
# ny=3 for all top results, so repeat with higher max ny
crossval_o2m_adjR2(Xtrain, ytrain, 1:2, 0:4, 2:4, nr_folds=5)
# nx=3 and ny=3:4, repeat with higher max ny
crossval_o2m_adjR2(Xtrain, ytrain, 1, 0:5, 2:5, nr_folds=5)
# n=1 nx=3 & ny=4 for best results, same results as for previous test

# Check with full cross-validation
crossval_o2m(Xtrain, ytrain, 1:2, 0:4, 0:4, nr_folds=5)
# Best at n=1 nx=0 ny=4
```


# Running PO2PLS

```{r}
Psteps2000_x1 <- PO2PLS(Xtrain, ytrain, 1, 3, 4, steps=2000)
save(Psteps2000_x1, "Psteps2000_x1", file="PO2PLSn1x3y4_ch10")
#load("PO2PLSn1x3y4")
```


```{r}
summary(Psteps2000_x1)
param <- Psteps2000_x1$parameters
```

```{r}
# Plot results
#plot(param$W[,1], param$W[,2], xlab="First component", ylab="Second component")
#abline(h=0)
#abline(v=0)
#plot(param$C[,1], param$C[,2], pch=as.character(1:7), xlab="First component", ylab="Second component")
#abline(h=0)
#abline(v=0)


# Plot the joined component
plot(param$W[,1])
# Plot the orthogonal components
plot(param$Wo[,1])
plot(param$Wo[,2])
plot(param$Wo[,3])

# Plot means and variance per gene
plot(colMeans(Xtrain))
vars <- apply(Xtrain, 2, var)
plot(vars, xlab = "Variance", main="Plot of variance per gene")

#sd(Xtrain%*%param$W[,1])
#sd(colSums(Xtrain))/sqrt(ncol(Xtrain))
```
```{r}
plot(param$W[,1], ylab="First component", main="Genes")
abline(h=0)
#plot(param$W[,2], ylab="Second component", main="Genes")
#abline(h=0)
plot(param$C[,1], ylab="First component", pch=as.character(1:7), main="Outcomes")
abline(h=0)
#plot(param$C[,2], ylab="Second component", pch=as.character(1:7), main="Outcomes")
#abline(h=0)
```

```{r}
# Compare with O2PLS results
O2PLS_res <- o2m(Xtrain, ytrain, 1, 3, 4)
summary(O2PLS_res)
# Plot joined components
plot(O2PLS_res, "Xj")
plot(O2PLS_res, "Yj")

# Plot specific component of X
plot(O2PLS_res, "Xo")

# It seems there is one area with extreme values, which ended up in the specific part in O2PLS and in the joined part in PO2PLS
```

```{r}
# Run SVD on Xtrain and plot results
SVD <- svd(Xtrain, 0, 10)
plot(SVD$v[,1])
plot(SVD$v[,2])
plot(SVD$v[,3])
plot(SVD$v[,4])
plot(SVD$v[,5])
```


To do

Gene Ontology (GO, look into it)
>GSEA (look into it) MAGMA/VEGAS
With specific parts and without specific parts (0)
Top genes!
```

